// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: proto/warehouse/warehouse.proto

package warehouse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Warehouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	ShopId        int32                  `protobuf:"varint,4,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warehouse) Reset() {
	*x = Warehouse{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warehouse) ProtoMessage() {}

func (x *Warehouse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warehouse.ProtoReflect.Descriptor instead.
func (*Warehouse) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{0}
}

func (x *Warehouse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Warehouse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Warehouse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Warehouse) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *Warehouse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Warehouse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Warehouse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Stock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	WarehouseId   int32                  `protobuf:"varint,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reserved      int32                  `protobuf:"varint,4,opt,name=reserved,proto3" json:"reserved,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{1}
}

func (x *Stock) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Stock) GetWarehouseId() int32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *Stock) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Stock) GetReserved() int32 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

func (x *Stock) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Stock) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   int32                  `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehouseRequest) Reset() {
	*x = GetWarehouseRequest{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehouseRequest) ProtoMessage() {}

func (x *GetWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehouseRequest.ProtoReflect.Descriptor instead.
func (*GetWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{2}
}

func (x *GetWarehouseRequest) GetWarehouseId() int32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

type GetWarehouseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouse     *Warehouse             `protobuf:"bytes,1,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehouseResponse) Reset() {
	*x = GetWarehouseResponse{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehouseResponse) ProtoMessage() {}

func (x *GetWarehouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehouseResponse.ProtoReflect.Descriptor instead.
func (*GetWarehouseResponse) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{3}
}

func (x *GetWarehouseResponse) GetWarehouse() *Warehouse {
	if x != nil {
		return x.Warehouse
	}
	return nil
}

type GetWarehousesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        int32                  `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	ActiveOnly    bool                   `protobuf:"varint,2,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehousesRequest) Reset() {
	*x = GetWarehousesRequest{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehousesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehousesRequest) ProtoMessage() {}

func (x *GetWarehousesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehousesRequest.ProtoReflect.Descriptor instead.
func (*GetWarehousesRequest) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{4}
}

func (x *GetWarehousesRequest) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *GetWarehousesRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type GetWarehousesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouses    []*Warehouse           `protobuf:"bytes,1,rep,name=warehouses,proto3" json:"warehouses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehousesResponse) Reset() {
	*x = GetWarehousesResponse{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehousesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehousesResponse) ProtoMessage() {}

func (x *GetWarehousesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehousesResponse.ProtoReflect.Descriptor instead.
func (*GetWarehousesResponse) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{5}
}

func (x *GetWarehousesResponse) GetWarehouses() []*Warehouse {
	if x != nil {
		return x.Warehouses
	}
	return nil
}

type CreateWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	ShopId        int32                  `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWarehouseRequest) Reset() {
	*x = CreateWarehouseRequest{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWarehouseRequest) ProtoMessage() {}

func (x *CreateWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWarehouseRequest.ProtoReflect.Descriptor instead.
func (*CreateWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWarehouseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWarehouseRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateWarehouseRequest) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type CreateWarehouseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouse     *Warehouse             `protobuf:"bytes,1,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWarehouseResponse) Reset() {
	*x = CreateWarehouseResponse{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWarehouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWarehouseResponse) ProtoMessage() {}

func (x *CreateWarehouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWarehouseResponse.ProtoReflect.Descriptor instead.
func (*CreateWarehouseResponse) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{7}
}

func (x *CreateWarehouseResponse) GetWarehouse() *Warehouse {
	if x != nil {
		return x.Warehouse
	}
	return nil
}

type UpdateWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   int32                  `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWarehouseRequest) Reset() {
	*x = UpdateWarehouseRequest{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWarehouseRequest) ProtoMessage() {}

func (x *UpdateWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWarehouseRequest.ProtoReflect.Descriptor instead.
func (*UpdateWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateWarehouseRequest) GetWarehouseId() int32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *UpdateWarehouseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWarehouseRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateWarehouseRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type UpdateWarehouseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouse     *Warehouse             `protobuf:"bytes,1,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWarehouseResponse) Reset() {
	*x = UpdateWarehouseResponse{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWarehouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWarehouseResponse) ProtoMessage() {}

func (x *UpdateWarehouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWarehouseResponse.ProtoReflect.Descriptor instead.
func (*UpdateWarehouseResponse) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateWarehouseResponse) GetWarehouse() *Warehouse {
	if x != nil {
		return x.Warehouse
	}
	return nil
}

type TransferStockRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProductId       int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	FromWarehouseId int32                  `protobuf:"varint,2,opt,name=from_warehouse_id,json=fromWarehouseId,proto3" json:"from_warehouse_id,omitempty"`
	ToWarehouseId   int32                  `protobuf:"varint,3,opt,name=to_warehouse_id,json=toWarehouseId,proto3" json:"to_warehouse_id,omitempty"`
	Quantity        int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferStockRequest) Reset() {
	*x = TransferStockRequest{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStockRequest) ProtoMessage() {}

func (x *TransferStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStockRequest.ProtoReflect.Descriptor instead.
func (*TransferStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{10}
}

func (x *TransferStockRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *TransferStockRequest) GetFromWarehouseId() int32 {
	if x != nil {
		return x.FromWarehouseId
	}
	return 0
}

func (x *TransferStockRequest) GetToWarehouseId() int32 {
	if x != nil {
		return x.ToWarehouseId
	}
	return 0
}

func (x *TransferStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type TransferStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferStockResponse) Reset() {
	*x = TransferStockResponse{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStockResponse) ProtoMessage() {}

func (x *TransferStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStockResponse.ProtoReflect.Descriptor instead.
func (*TransferStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{11}
}

func (x *TransferStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	WarehouseId   int32                  `protobuf:"varint,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{12}
}

func (x *GetStockRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetStockRequest) GetWarehouseId() int32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

type GetStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *Stock                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockResponse) Reset() {
	*x = GetStockResponse{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResponse) ProtoMessage() {}

func (x *GetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResponse.ProtoReflect.Descriptor instead.
func (*GetStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{13}
}

func (x *GetStockResponse) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

type UpdateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	WarehouseId   int32                  `protobuf:"varint,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reserved      int32                  `protobuf:"varint,4,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Operation     string                 `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"` // "add", "subtract", "set"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateStockRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateStockRequest) GetWarehouseId() int32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *UpdateStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateStockRequest) GetReserved() int32 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

func (x *UpdateStockRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type UpdateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Stock         *Stock                 `protobuf:"bytes,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockResponse) Reset() {
	*x = UpdateStockResponse{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockResponse) ProtoMessage() {}

func (x *UpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateStockResponse) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

var File_proto_warehouse_warehouse_proto protoreflect.FileDescriptor

const file_proto_warehouse_warehouse_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/warehouse/warehouse.proto\x12\twarehouse\"\xba\x01\n" +
	"\tWarehouse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x17\n" +
	"\ashop_id\x18\x04 \x01(\x05R\x06shopId\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xbf\x01\n" +
	"\x05Stock\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\x05R\vwarehouseId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1a\n" +
	"\breserved\x18\x04 \x01(\x05R\breserved\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"8\n" +
	"\x13GetWarehouseRequest\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x05R\vwarehouseId\"J\n" +
	"\x14GetWarehouseResponse\x122\n" +
	"\twarehouse\x18\x01 \x01(\v2\x14.warehouse.WarehouseR\twarehouse\"P\n" +
	"\x14GetWarehousesRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\x05R\x06shopId\x12\x1f\n" +
	"\vactive_only\x18\x02 \x01(\bR\n" +
	"activeOnly\"M\n" +
	"\x15GetWarehousesResponse\x124\n" +
	"\n" +
	"warehouses\x18\x01 \x03(\v2\x14.warehouse.WarehouseR\n" +
	"warehouses\"a\n" +
	"\x16CreateWarehouseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x17\n" +
	"\ashop_id\x18\x03 \x01(\x05R\x06shopId\"M\n" +
	"\x17CreateWarehouseResponse\x122\n" +
	"\twarehouse\x18\x01 \x01(\v2\x14.warehouse.WarehouseR\twarehouse\"\x83\x01\n" +
	"\x16UpdateWarehouseRequest\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x05R\vwarehouseId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\"M\n" +
	"\x17UpdateWarehouseResponse\x122\n" +
	"\twarehouse\x18\x01 \x01(\v2\x14.warehouse.WarehouseR\twarehouse\"\xa5\x01\n" +
	"\x14TransferStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12*\n" +
	"\x11from_warehouse_id\x18\x02 \x01(\x05R\x0ffromWarehouseId\x12&\n" +
	"\x0fto_warehouse_id\x18\x03 \x01(\x05R\rtoWarehouseId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"K\n" +
	"\x15TransferStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"S\n" +
	"\x0fGetStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\x05R\vwarehouseId\":\n" +
	"\x10GetStockResponse\x12&\n" +
	"\x05stock\x18\x01 \x01(\v2\x10.warehouse.StockR\x05stock\"\xac\x01\n" +
	"\x12UpdateStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\x05R\vwarehouseId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1a\n" +
	"\breserved\x18\x04 \x01(\x05R\breserved\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\"W\n" +
	"\x13UpdateStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x05stock\x18\x02 \x01(\v2\x10.warehouse.StockR\x05stock2\xd2\x04\n" +
	"\x10WarehouseService\x12O\n" +
	"\fGetWarehouse\x12\x1e.warehouse.GetWarehouseRequest\x1a\x1f.warehouse.GetWarehouseResponse\x12R\n" +
	"\rGetWarehouses\x12\x1f.warehouse.GetWarehousesRequest\x1a .warehouse.GetWarehousesResponse\x12X\n" +
	"\x0fCreateWarehouse\x12!.warehouse.CreateWarehouseRequest\x1a\".warehouse.CreateWarehouseResponse\x12X\n" +
	"\x0fUpdateWarehouse\x12!.warehouse.UpdateWarehouseRequest\x1a\".warehouse.UpdateWarehouseResponse\x12R\n" +
	"\rTransferStock\x12\x1f.warehouse.TransferStockRequest\x1a .warehouse.TransferStockResponse\x12C\n" +
	"\bGetStock\x12\x1a.warehouse.GetStockRequest\x1a\x1b.warehouse.GetStockResponse\x12L\n" +
	"\vUpdateStock\x12\x1d.warehouse.UpdateStockRequest\x1a\x1e.warehouse.UpdateStockResponseB\rZ\v.;warehouseb\x06proto3"

var (
	file_proto_warehouse_warehouse_proto_rawDescOnce sync.Once
	file_proto_warehouse_warehouse_proto_rawDescData []byte
)

func file_proto_warehouse_warehouse_proto_rawDescGZIP() []byte {
	file_proto_warehouse_warehouse_proto_rawDescOnce.Do(func() {
		file_proto_warehouse_warehouse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_warehouse_warehouse_proto_rawDesc), len(file_proto_warehouse_warehouse_proto_rawDesc)))
	})
	return file_proto_warehouse_warehouse_proto_rawDescData
}

var file_proto_warehouse_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_warehouse_warehouse_proto_goTypes = []any{
	(*Warehouse)(nil),               // 0: warehouse.Warehouse
	(*Stock)(nil),                   // 1: warehouse.Stock
	(*GetWarehouseRequest)(nil),     // 2: warehouse.GetWarehouseRequest
	(*GetWarehouseResponse)(nil),    // 3: warehouse.GetWarehouseResponse
	(*GetWarehousesRequest)(nil),    // 4: warehouse.GetWarehousesRequest
	(*GetWarehousesResponse)(nil),   // 5: warehouse.GetWarehousesResponse
	(*CreateWarehouseRequest)(nil),  // 6: warehouse.CreateWarehouseRequest
	(*CreateWarehouseResponse)(nil), // 7: warehouse.CreateWarehouseResponse
	(*UpdateWarehouseRequest)(nil),  // 8: warehouse.UpdateWarehouseRequest
	(*UpdateWarehouseResponse)(nil), // 9: warehouse.UpdateWarehouseResponse
	(*TransferStockRequest)(nil),    // 10: warehouse.TransferStockRequest
	(*TransferStockResponse)(nil),   // 11: warehouse.TransferStockResponse
	(*GetStockRequest)(nil),         // 12: warehouse.GetStockRequest
	(*GetStockResponse)(nil),        // 13: warehouse.GetStockResponse
	(*UpdateStockRequest)(nil),      // 14: warehouse.UpdateStockRequest
	(*UpdateStockResponse)(nil),     // 15: warehouse.UpdateStockResponse
}
var file_proto_warehouse_warehouse_proto_depIdxs = []int32{
	0,  // 0: warehouse.GetWarehouseResponse.warehouse:type_name -> warehouse.Warehouse
	0,  // 1: warehouse.GetWarehousesResponse.warehouses:type_name -> warehouse.Warehouse
	0,  // 2: warehouse.CreateWarehouseResponse.warehouse:type_name -> warehouse.Warehouse
	0,  // 3: warehouse.UpdateWarehouseResponse.warehouse:type_name -> warehouse.Warehouse
	1,  // 4: warehouse.GetStockResponse.stock:type_name -> warehouse.Stock
	1,  // 5: warehouse.UpdateStockResponse.stock:type_name -> warehouse.Stock
	2,  // 6: warehouse.WarehouseService.GetWarehouse:input_type -> warehouse.GetWarehouseRequest
	4,  // 7: warehouse.WarehouseService.GetWarehouses:input_type -> warehouse.GetWarehousesRequest
	6,  // 8: warehouse.WarehouseService.CreateWarehouse:input_type -> warehouse.CreateWarehouseRequest
	8,  // 9: warehouse.WarehouseService.UpdateWarehouse:input_type -> warehouse.UpdateWarehouseRequest
	10, // 10: warehouse.WarehouseService.TransferStock:input_type -> warehouse.TransferStockRequest
	12, // 11: warehouse.WarehouseService.GetStock:input_type -> warehouse.GetStockRequest
	14, // 12: warehouse.WarehouseService.UpdateStock:input_type -> warehouse.UpdateStockRequest
	3,  // 13: warehouse.WarehouseService.GetWarehouse:output_type -> warehouse.GetWarehouseResponse
	5,  // 14: warehouse.WarehouseService.GetWarehouses:output_type -> warehouse.GetWarehousesResponse
	7,  // 15: warehouse.WarehouseService.CreateWarehouse:output_type -> warehouse.CreateWarehouseResponse
	9,  // 16: warehouse.WarehouseService.UpdateWarehouse:output_type -> warehouse.UpdateWarehouseResponse
	11, // 17: warehouse.WarehouseService.TransferStock:output_type -> warehouse.TransferStockResponse
	13, // 18: warehouse.WarehouseService.GetStock:output_type -> warehouse.GetStockResponse
	15, // 19: warehouse.WarehouseService.UpdateStock:output_type -> warehouse.UpdateStockResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_warehouse_warehouse_proto_init() }
func file_proto_warehouse_warehouse_proto_init() {
	if File_proto_warehouse_warehouse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_warehouse_warehouse_proto_rawDesc), len(file_proto_warehouse_warehouse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_warehouse_warehouse_proto_goTypes,
		DependencyIndexes: file_proto_warehouse_warehouse_proto_depIdxs,
		MessageInfos:      file_proto_warehouse_warehouse_proto_msgTypes,
	}.Build()
	File_proto_warehouse_warehouse_proto = out.File
	file_proto_warehouse_warehouse_proto_goTypes = nil
	file_proto_warehouse_warehouse_proto_depIdxs = nil
}
