// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: proto/shop/shop.proto

package shop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerId       int32                  `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shop) Reset() {
	*x = Shop{}
	mi := &file_proto_shop_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shop) ProtoMessage() {}

func (x *Shop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shop.ProtoReflect.Descriptor instead.
func (*Shop) Descriptor() ([]byte, []int) {
	return file_proto_shop_shop_proto_rawDescGZIP(), []int{0}
}

func (x *Shop) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Shop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Shop) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Shop) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Shop) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Shop) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateShopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	OwnerId       int32                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShopRequest) Reset() {
	*x = CreateShopRequest{}
	mi := &file_proto_shop_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShopRequest) ProtoMessage() {}

func (x *CreateShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShopRequest.ProtoReflect.Descriptor instead.
func (*CreateShopRequest) Descriptor() ([]byte, []int) {
	return file_proto_shop_shop_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShopRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateShopRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateShopRequest) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type CreateShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shop          *Shop                  `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShopResponse) Reset() {
	*x = CreateShopResponse{}
	mi := &file_proto_shop_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShopResponse) ProtoMessage() {}

func (x *CreateShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShopResponse.ProtoReflect.Descriptor instead.
func (*CreateShopResponse) Descriptor() ([]byte, []int) {
	return file_proto_shop_shop_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShopResponse) GetShop() *Shop {
	if x != nil {
		return x.Shop
	}
	return nil
}

type GetShopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        int32                  `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopRequest) Reset() {
	*x = GetShopRequest{}
	mi := &file_proto_shop_shop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopRequest) ProtoMessage() {}

func (x *GetShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_shop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopRequest.ProtoReflect.Descriptor instead.
func (*GetShopRequest) Descriptor() ([]byte, []int) {
	return file_proto_shop_shop_proto_rawDescGZIP(), []int{3}
}

func (x *GetShopRequest) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type GetShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shop          *Shop                  `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopResponse) Reset() {
	*x = GetShopResponse{}
	mi := &file_proto_shop_shop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopResponse) ProtoMessage() {}

func (x *GetShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_shop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopResponse.ProtoReflect.Descriptor instead.
func (*GetShopResponse) Descriptor() ([]byte, []int) {
	return file_proto_shop_shop_proto_rawDescGZIP(), []int{4}
}

func (x *GetShopResponse) GetShop() *Shop {
	if x != nil {
		return x.Shop
	}
	return nil
}

type GetShopsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       int32                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopsRequest) Reset() {
	*x = GetShopsRequest{}
	mi := &file_proto_shop_shop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopsRequest) ProtoMessage() {}

func (x *GetShopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_shop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopsRequest.ProtoReflect.Descriptor instead.
func (*GetShopsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shop_shop_proto_rawDescGZIP(), []int{5}
}

func (x *GetShopsRequest) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *GetShopsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetShopsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetShopsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shops         []*Shop                `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopsResponse) Reset() {
	*x = GetShopsResponse{}
	mi := &file_proto_shop_shop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopsResponse) ProtoMessage() {}

func (x *GetShopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_shop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopsResponse.ProtoReflect.Descriptor instead.
func (*GetShopsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shop_shop_proto_rawDescGZIP(), []int{6}
}

func (x *GetShopsResponse) GetShops() []*Shop {
	if x != nil {
		return x.Shops
	}
	return nil
}

func (x *GetShopsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetShopsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetShopsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_proto_shop_shop_proto protoreflect.FileDescriptor

const file_proto_shop_shop_proto_rawDesc = "" +
	"\n" +
	"\x15proto/shop/shop.proto\x12\x04shop\"\xa5\x01\n" +
	"\x04Shop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\x05R\aownerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"d\n" +
	"\x11CreateShopRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x05R\aownerId\"4\n" +
	"\x12CreateShopResponse\x12\x1e\n" +
	"\x04shop\x18\x01 \x01(\v2\n" +
	".shop.ShopR\x04shop\")\n" +
	"\x0eGetShopRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\x05R\x06shopId\"1\n" +
	"\x0fGetShopResponse\x12\x1e\n" +
	"\x04shop\x18\x01 \x01(\v2\n" +
	".shop.ShopR\x04shop\"V\n" +
	"\x0fGetShopsRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x05R\aownerId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"t\n" +
	"\x10GetShopsResponse\x12 \n" +
	"\x05shops\x18\x01 \x03(\v2\n" +
	".shop.ShopR\x05shops\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit2\xc1\x01\n" +
	"\vShopService\x12?\n" +
	"\n" +
	"CreateShop\x12\x17.shop.CreateShopRequest\x1a\x18.shop.CreateShopResponse\x126\n" +
	"\aGetShop\x12\x14.shop.GetShopRequest\x1a\x15.shop.GetShopResponse\x129\n" +
	"\bGetShops\x12\x15.shop.GetShopsRequest\x1a\x16.shop.GetShopsResponseB\bZ\x06.;shopb\x06proto3"

var (
	file_proto_shop_shop_proto_rawDescOnce sync.Once
	file_proto_shop_shop_proto_rawDescData []byte
)

func file_proto_shop_shop_proto_rawDescGZIP() []byte {
	file_proto_shop_shop_proto_rawDescOnce.Do(func() {
		file_proto_shop_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shop_shop_proto_rawDesc), len(file_proto_shop_shop_proto_rawDesc)))
	})
	return file_proto_shop_shop_proto_rawDescData
}

var file_proto_shop_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_shop_shop_proto_goTypes = []any{
	(*Shop)(nil),               // 0: shop.Shop
	(*CreateShopRequest)(nil),  // 1: shop.CreateShopRequest
	(*CreateShopResponse)(nil), // 2: shop.CreateShopResponse
	(*GetShopRequest)(nil),     // 3: shop.GetShopRequest
	(*GetShopResponse)(nil),    // 4: shop.GetShopResponse
	(*GetShopsRequest)(nil),    // 5: shop.GetShopsRequest
	(*GetShopsResponse)(nil),   // 6: shop.GetShopsResponse
}
var file_proto_shop_shop_proto_depIdxs = []int32{
	0, // 0: shop.CreateShopResponse.shop:type_name -> shop.Shop
	0, // 1: shop.GetShopResponse.shop:type_name -> shop.Shop
	0, // 2: shop.GetShopsResponse.shops:type_name -> shop.Shop
	1, // 3: shop.ShopService.CreateShop:input_type -> shop.CreateShopRequest
	3, // 4: shop.ShopService.GetShop:input_type -> shop.GetShopRequest
	5, // 5: shop.ShopService.GetShops:input_type -> shop.GetShopsRequest
	2, // 6: shop.ShopService.CreateShop:output_type -> shop.CreateShopResponse
	4, // 7: shop.ShopService.GetShop:output_type -> shop.GetShopResponse
	6, // 8: shop.ShopService.GetShops:output_type -> shop.GetShopsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_shop_shop_proto_init() }
func file_proto_shop_shop_proto_init() {
	if File_proto_shop_shop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shop_shop_proto_rawDesc), len(file_proto_shop_shop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shop_shop_proto_goTypes,
		DependencyIndexes: file_proto_shop_shop_proto_depIdxs,
		MessageInfos:      file_proto_shop_shop_proto_msgTypes,
	}.Build()
	File_proto_shop_shop_proto = out.File
	file_proto_shop_shop_proto_goTypes = nil
	file_proto_shop_shop_proto_depIdxs = nil
}
